### ISSUE TITLE
Shelly RGBW2 in white mode doesn't get configured relay names for its entities

### ISSUE THREAD

**Issue by Bascht74** [bieniu/ha-shellies-discovery#101]
**Describe the bug**

Set a Shelly RGBW2 for "white" mode and set relay names:

```
      shellyrgbw2-1E0600:
        mode: "white" 
        relay-0: "light"
        relay-0-name: "Lampe.OG.Kara.Bett"
        relay-1-name: "disabled1"
        relay-2-name: "disabled2"
        relay-3-name: "disabled3"
```

**Expected behavior**

See the customized entity names from the yaml-file. 
But I get the "default" names:
![image](https://user-images.githubusercontent.com/66269310/101267795-383dea00-375d-11eb-985e-5fa4f9052c21.png)
 

**Versions:**
 - Home Assistant: 0.118
 - Shellies Discovery: Version 0.34.0 (installed via HACS)
 - Shelly device firmware: 1.93RC2

**Shellies Discovery automation:**

how can I do that? What do you mean? I will check in your documentation an add the information, if I get it right.

```yaml
     shellyrgbw2-1E0600:
        mode: "white" 
        relay-0: "light"
        relay-0-name: "Lampe.OG.Kara.Bett"
        relay-1-name: "disabled1"
        relay-2-name: "disabled2"
        relay-3-name: "disabled3"
```

**Debug log:**

how to do that? I will check in your documentation and add the information, if I get it right.

```txt

```

**Comment by bieniu** [comment]
https://github.com/bieniu/ha-shellies-discovery/issues/80

**Comment by Bascht74** [comment]
@bieniu Thx. I didn't get that directly out of your documentation

Could you add your example in #80 to your "Custom configuration example"?

```
shellyrgbw2-BC0640:
  mode: "white"
  light-1-name: "Living room"
  light-2-name: "Bedroom"
  light-3-name: "Kitchen"
```

and an info to your Device arguments

light-<NUM>-name | True | string | None | string | friendly name of the light number NUM. **Use this key as well for Shelly RGBW2**
