### ISSUE TITLE
All of sudden one of my Shelly DW2 shows unavailable for open/close

### ISSUE THREAD

**Issue by denniswham** [bieniu/ha-shellies-discovery#106]
**Describe the bug**

**Expected behavior**

**Versions:**
 - Home Assistant: Home Assistant 2020.12.1
 - Shellies Discovery: 0.35.5
 - Shelly device firmware: 20201126-143533/v1.9.1@6d969d45+

**Shellies Discovery automation:**

```
  - id: 9d090e06-286a-437d-9e76-810f938782f0
    alias: '[Shelly] Shellies Discovery'
    mode: queued
    max: 999
    trigger:
      platform: mqtt
      topic: shellies/announce
    action:
      service: python_script.shellies_discovery
      data_template:
        id: '{{ trigger.payload_json.id }}'
        mac: '{{ trigger.payload_json.mac }}'
        fw_ver: '{{ trigger.payload_json.fw_ver }}'
        model: '{{ trigger.payload_json.model }}'
        discovery_prefix: 'homeassistant'
        qos: 0
        shellyplug-s-8013CD:
          relay-0: "switch"
          relay-0-name: "Living Room Amplifier"
          force_update_sensors: true
        shellyplug-s-8016CB:
          relay-0: "light"
          relay-0-name: "Christmas Tree"
          force_update_sensors: true
        shellyplug-s-XXXXXX:
          relay-0: "switch"
          relay-0-name: "Attic Washing Machine"
          force_update_sensors: true
        shellyplug-s-XXXXXX:
          relay-0: "switch"
          relay-0-name: "Attic Tumble Dryer"
          force_update_sensors: true
        shellyswitch25-XXXXXX:
          mode: "roller"
          roller-0-name: "Master Bedroom Roller Shutter"
          force_update_sensors: true
        shellyswitch25-XXXXXX
          mode: "roller"
          roller-0-name: "Lucas Room Roller Shutter"
          force_update_sensors: true
        shellyswitch25-XXXXXX:
          mode: "roller"
          roller-0-name: "Backyard Awning"
          force_update_sensors: true
        shellydimmer-XXXXXX:
          light-0-name: "Kitchen Light"
          force_update_sensors: true
        shellydimmer-XXXXXX:
          light-0-name: "Living Room Wall Light"
          force_update_sensors: true
        shellydimmer2-XXXXXXXXXXXX:
          light-0-name: "Living Room Dining Table Light"
          force_update_sensors: true
        shellydimmer-XXXXXX:
          light-0-name: "Living Room Spot Light"
          force_update_sensors: true
        shellydimmer-XXXXXX:
          light-0-name: "Living Room Led Strip"
          force_update_sensors: true
        shellydimmer-XXXXXX:
          light-0-name: "Office Spot Light"
          force_update_sensors: true
        shelly1pm-XXXXXX:
          relay-0: "light"
          relay-0-name: "Hallway Light"
          push_off_delay: false
          force_update_sensors: true
        shelly1pm-XXXXXX:
          relay-0: "light"
          relay-0-name: "Timos Room Light"
          push_off_delay: false
          force_update_sensors: true
        shelly1pm-XXXXXX:
          relay-0: "light"
          relay-0-name: "Backyard Wall Lights"
          push_off_delay: false
          force_update_sensors: true
        shellyswitch25-XXXXXXXXXXXX:
          mode: "relay"
          relay-0: light
          relay-1: light
          relay-0-name: "Master Bedroom Wall Lights"
          relay-1-name: "Master Bedroom Wardrobe Lights"
          push_off_delay: false
          force_update_sensors: true
        shellydimmer2-XXXXXXXXXXXX:
          light-0-name: "Entryway Wall Light"
          force_update_sensors: true
        shelly1pm-XXXXXXXXXXXX:
          relay-0: "light"
          relay-0-name: "Entryway Light"
          push_off_delay: false
          force_update_sensors: true
        shellydimmer2-XXXXXXXXXXXX:
          light-0-name: "Office LED Strip"
          force_update_sensors: true
        shelly1pm-XXXXXXXXXXXX:
          relay-0: "light"
          relay-0-name: "Backyard Garden Light"
          push_off_delay: false
          force_update_sensors: true
        shellydimmer2-XXXXXXXXXXXX:
          light-0-name: "Bathroom Light"
          force_update_sensors: true
        shellyswitch25-XXXXXXXXXXXX:
          mode: "relay"
          relay-0: light
          relay-1: light
          relay-0-name: "Lucas Room Light"
          relay-1-name: "Lucas Room Wall Light"
          push_off_delay: false
          force_update_sensors: true
        shellyswitch25-XXXXXXXXXXXX:
          mode: "relay"
          relay-0: light
          relay-1: light
          relay-0-name: "Living Room TV Light"
          relay-1-name: "Living Room Painting Light"
          push_off_delay: false
          force_update_sensors: true
        shelly1pm-XXXXXXXXXXXX:
          relay-0: "light"
          relay-0-name: "Office Painting Light"
          push_off_delay: false
          force_update_sensors: true
        ShellyBulbDuo-XXXXXX:
          light-0-name: "Emilie Room Light"
          force_update_sensors: true
        ShellyBulbDuo-XXXXXX:
          light-0-name: "Lucas Room Floor Light"
          force_update_sensors: true
```

**Debug log:**

```
I have two DW2 devices, same setup. For both I have enabled retain, to have the sensors' values after a HA restart. That works well. But for some reason after some hours of the devices being in deep sleep, for one of the two DW2 sensors the "_sensor_opening" entity becomes unavailable. The other entities of the same device are still showing values.
For the other DW2 device, this issue is not happening.
```
