### ISSUE TITLE
Shelly H&T Fw 1.11.1 ext_power 

### ISSUE THREAD

**Issue by Veldkornet** [bieniu/ha-shellies-discovery#133]
**Describe the bug**

Since Fw 1.11.1, my Shelly H&T's now have a new MQTT field called **ext_power**. Additionally, the **batter**y value is now shown as **-1**. This new ext_power should be added to the MQTT script as it's currently showing the battery as -1.

![image](https://user-images.githubusercontent.com/10297361/126996730-c3897cf9-5360-4344-a1e8-7f696a7ac9ae.png)

**Expected behavior**

External Power should be shown.

**Versions:**
 - Home Assistant: core-2021.7.4
 - Shellies Discovery: core-2021.7.4
 - Shelly device firmware: 20210723-154419/v1.11.1-gc2e1500

**Shellies Discovery automation:**

```yaml
# configuration.yaml file
python_script:

# automations.yaml file
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
```

**Debug log:**

```txt

```
