### ISSUE TITLE
Brightness cannot be set on Shelly Vintage

### ISSUE THREAD

**Issue by olympia** [bieniu/ha-shellies-discovery#137]
**Describe the bug**

 Shelly Vintage seems to be discovered only as an on/off light. Brightness cannot be set (and also cannot be turned on by setting the brightness to 100%) and it can only be turned on/off with the light switch.

**Expected behavior**

  I expect that the brightness should be set, just like prior to the Shelly FW update to v1.11.2-rc1 and Shellies Discovery 0.39.x.
  All other shellies are working correctly.

**Versions:**
 - Home Assistant: core-2021.8.2
 - Shellies Discovery: Version 0.40.2
 - Shelly device firmware: v1.11.2-rc1

**Shellies Discovery automation:**
alias: Shellies Discovery
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode }}'

**Debug log:**

  Attached
[x.txt](https://github.com/bieniu/ha-shellies-discovery/files/6948104/x.txt)

**Comment by olympia** [comment]
Could this be related?
https://community.home-assistant.io/t/mqtt-light-invalid-brightness-value-received/244650
I am having the same `[homeassistant.components.mqtt.light.schema_template] Invalid white value received` messages in the log.

**Comment by bieniu** [comment]
Please use correct `shellies discovery` automation https://github.com/bieniu/ha-shellies-discovery#minimal-configuration

There were no changes in the script for Vintage brightness. Please show me list of MQTT topics/payloads when you try to change brightness.

**Comment by olympia** [comment]
OK, fixed, the automation, but it hasn't resolved the issue.

I just tried a second Vintage Bulb using the 20210727-153103/v1.11.2-rc1 firmware with the the same result. All other shellies (I have a lot) are working perfectly.

Following that I downgraded shellies discovery to 0.39.6, the issue persisted.
Then I downgraded the Vintage firmware back to 20210429-100039/v1.10.4 (last stable) and it started to work.

So Vintage firmware 20210429-100039/v1.10.4 with shellies discovery v0.39.6 works perfectly.

So I guess there are two options: either Shelly screwed up something in the rc firmware or they have a breaking change?

Can you please help me how shall I "show yout the list of MQTT topics/payloads"? From where should I get that?

**Comment by bieniu** [comment]
> Following that I downgraded shellies discovery to 0.39.6, the issue persisted.
> So Vintage firmware 20210429-100039/v1.10.4 with shellies discovery v0.39.6 works perfectly.

So firmware v1.11.2-rc1 is a problem. Maybe this is a reason it is not available for users yet.

**Comment by bieniu** [comment]
Try 1.11.4-rc firmware http://repo.shelly.cloud/firmware/rc/

**Comment by olympia** [comment]
Hi Maciej, I am off the country on vacation now; I will be able to test this next weekend and I will report back.

**Comment by olympia** [comment]
Just tried, unfortunately it's not ok with the same symptom with 1.11.4-rc2 released today

**Comment by olympia** [comment]
...but interestingly (not sure why) at least shellies-discovery now detects the vintage with it's latest stable firmware 20210429-100039/v1.10.4, os I don't need to downgrade to v0.39.6 in order to get the vintage work.

**Comment by olympia** [comment]
I've just tried with 20210901-201645/v1.11.4-rc3-gf11bc53 and the issue is still persisting. 
Need to downgrade back to 20210901-201645/v1.11.4-rc3-gf11bc53 in order to get the vintage brightess manipulation working.

**Comment by adriaanh** [comment]
I seem to have the same problem, with firmware 20210909-143814/v1.11.4-DNSfix-ge6b2f6d. Is there anyway a workaround?

**Comment by bieniu** [comment]
I need some payloads from MQTT broker after brightness change. Without this data, I can't help because I don't have this device.

**Comment by adriaanh** [comment]
From the Home Assistant UI I get the following. It this what you are looking for?

```
schema: template
name: Shelly Vintage 6F570F Light 0
command_topic: shellies/ShellyVintage-6F570F/light/0/set
state_topic: shellies/ShellyVintage-6F570F/light/0/status
availability_topic: shellies/ShellyVintage-6F570F/online
payload_available: 'true'
payload_not_available: 'false'
command_on_template: >-
  {"turn":"on"{%if brightness is
  defined%},"brightness":{{brightness|float|multiply(0.3922)|round}}{%endif%}{%if
  transition is
  defined%},"transition":{{min(transition|multiply(1000),4999)}}{%endif%}}
command_off_template: >-
  {"turn":"off"{%if transition is
  defined%},"transition":{{min(transition,4999)|multiply(1000)}}{%endif%}}
state_template: '{%if value_json.ison%}on{%else%}off{%endif%}'
brightness_template: '{{value_json.brightness|float|multiply(2.55)|round}}'
unique_id: shellyvintage-6f570f-light-0
qos: '2'
device:
  identifiers:
    - ecfabc6f570f
  name: Shelly Vintage 6F570F
  model: Shelly Vintage
  sw_version: 20210909-143814/v1.11.4-DNSfix-ge6b2f6d
  manufacturer: Allterco Robotics
platform: mqtt
```
