### ISSUE TITLE
unit_of_measurement not reflecting Shelly configuration

### ISSUE THREAD

**Issue by gobigdave** [bieniu/ha-shellies-discovery#143]
**Describe the bug**
I don't know if this is a discovery bug or possibly Shelly. I have an H&T configured to use F for temperatures. However, the discovery config received by HA is:

name: Shelly H&T familyroom Temperature
state_topic: shellies/shellyht-familyroom/sensor/temperature
force_update: 'False'
enabled_by_default: 'True'
unique_id: shellyht-familyroom-temperature
qos: 0
device:
  identifiers:
    - e0980695711d
  name: Shelly H&T familyroom
  model: Shelly H&T
  sw_version: 20210723-154419/v1.11.1-gc2e1500
  manufacturer: Allterco Robotics
state_class: measurement
unit_of_measurement: °C
device_class: temperature
value_template: '{{value|float|round(1)}}'
expire_after: 51839
platform: mqtt

The payload for the temperature is 72F. However, even though I setup customization for unit_of_measurement in HA, my temps all display converted to C.

This conversion didn't happen prior to HA version 2021-09-01. It looks like HA may be using the unit_of_measurement from the config and then converting to whatever units HA is setup for (F in my case).

**Expected behavior**
I expect that if my Shelly is configured for F, the unit_of_measurement in the discovery config will be F.

**Versions:**
 - Home Assistant: 2021-09-01
 - Shellies Discovery: 2021.9
 - Shelly device firmware: 1.11.1

**Shellies Discovery automation:**

```
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
```

**Debug log:**

```tx
```
