### ISSUE TITLE
Shelly motion doesn't reply to announce (by design) , becomes unavailable 

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#147]
**Describe the bug**
Shelly Motion does not reply to announce.
I have opened a ticket with Shelly and they replied by saying that this is normal and is done to prevent battery draining.
Shelly Motion only sends and announce message when it boots or when reconnects to wifi

If HA or the MQTT broker is rebooted the sensor becomes unavailable even when configured to be battery operated 

**Expected behavior**
The device and entities should not become unavailable

**Versions:**
 - Home Assistant: 2021.9.5
 - Shellies Discovery:  0.40.4
 - Shelly device firmware:  20210725-085052/v1.1.3-rc16@4899605c

**Shellies Discovery automation:**

```yaml
alias: Shellies Discovery
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      qos: 2
      livingroom-motion:
        powered: battery
      kitchen-motion:
        powered: battery

```

**Debug log:**

```txt

```
