### ISSUE TITLE
Flood and Door/Window not picking up temperature

### ISSUE THREAD

**Issue by gobigdave** [bieniu/ha-shellies-discovery#153]
**Describe the bug**
Both Shelly Flood and D/W include temperature in their specs:
shellies/shellyflood-<deviceid>/sensor/temperature in °C or °F depending on configuration

I added a custom config to the discovery automation

use_fahrenheit: true

For my floods and D/W sensors. This setting worked with my H/T settings so HA correctly handles the temperature.

However, for my flood and D/W sensors, I do not see any mention of temperature in MQTT info or an entity.

**Expected behavior**
I expected to see temperature given the sensors are publishing the info.

**Versions:**
 - Home Assistant: 2021.9.7
 - Shellies Discovery: 0.40.9
 - Shelly device firmware: Latest

**Shellies Discovery automation:**
```

- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/2"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      shellyht-956F4F:
        use_fahrenheit: true
      shellyht-95711D:
        use_fahrenheit: true
      shellyflood-F2A871:
        use_fahrenheit: true
      shellyflood-6A78CE:
        use_fahrenheit: true
      shellydw2-AAB70B:
        use_fahrenheit: true
```

**Debug log:**

```txt

```
