### ISSUE TITLE
Shelly Plug device not added

### ISSUE THREAD

**Issue by alberanid** [bieniu/ha-shellies-discovery#210]
**Describe the bug**

I have a couple of Shelly Plug which are not added to the Home Assistant list of devices.

**Expected behavior**

Device added to Home Assistant.

**Versions:**
 - Home Assistant: 2021.12.7
 - Shellies Discovery: 0.42.9
 - Shelly device firmware: 20211109-130708/v1.11.7-g682a0db

**Shellies Discovery automation:**

```yaml
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  trigger:
  - platform: mqtt
    topic: shellies/announce
  action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      discovery_prefix: hass
      qos: 2
      shellyplug-washer:
        relay-0: switch
```

**Debug log:**

See this log from Home Assistant, for one of the devices: 
[shelly-plug-discovery.log](https://github.com/bieniu/ha-shellies-discovery/files/7799032/shelly-plug-discovery.log)

I can provide more information and perform some testing, if needed.

Thanks for your support!
