### ISSUE TITLE
Longpush entity no longer being reported

### ISSUE THREAD

**Issue by lukcz** [bieniu/ha-shellies-discovery#217]
**Describe the bug**
  After updating to  0.43.0 entity Longpush no longer works. Reverting to 0.42.9 fixed the issue. I was using Shelly 1.

**Expected behavior**
  Holding momentary switch longer than the predefined number of secs will result in entity Longpush being on for short period of time.

**Versions:**
 - Home Assistant: Home Assistant 2021.12.7
 - Shellies Discovery: 0.43.0
 - Shelly device firmware:  20211109-124958/v1.11.7-g682a0db 

**Shellies Discovery automation:**

```yaml
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      shelly1-B9216F:
        relay-0: switch
        relay-0-name: Bathrom Floor Heating
```
