### ISSUE TITLE
ValueError: host value None is not valid

### ISSUE THREAD

**Issue by plumped** [bieniu/ha-shellies-discovery#219]
**Describe the bug**

Error executing script: host value None is not valid, update shallies_discovery automation

Maybe im missing something here...

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 912, in <module>
ValueError: host value None is not valid, update shallies_discovery automation

**Versions:**
 - Home Assistant:  core-2021.12.7
 - Shellies Discovery: 0.43.1
 - Shelly device firmware:  20211109-124958/v1.11.7-g682a0db

**Shellies Discovery automation:**
The automations are not visible in Automations or Scripts... thats already strange

```yaml  (That all because i have set up Homeassistant completely new)

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

```

Thx a lot!
