### ISSUE TITLE
Input states not working for Shelly 1PM

### ISSUE THREAD

**Issue by Eyco1981** [bieniu/ha-shellies-discovery#220]
**Describe the bug**
Missing input states for Shelly 1PM and device triggers not usable for input events.

**Expected behavior**
Input states of Shelly 1PM updating when toggling the physical switch.
Device triggers (input turned on/off) usable in automations.

**Versions:**
 - Home Assistant: 2021.12.7
 - Shellies Discovery:  0.43.1
 - Shelly device firmware:  20211109-130756/v1.11.7-g682a0db

**Shellies Discovery automation:**
```
alias: 'MQTT: Shellies Discovery'
description: ''
trigger:
  - platform: mqtt
    topic: shellies/announce
condition: []
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
mode: queued
max: 999
```
