### ISSUE TITLE
Shelly Button1 triggering twice?

### ISSUE THREAD

**Issue by TheGroundZero** [bieniu/ha-shellies-discovery#238]
**Describe the bug**

I have a Node-RED flow that's triggered by double-clicking the Shelly Button1.
For some reason, the flow is triggered twice, toggling my lights twice (thus on and back off).

I monitored the MQTT messages and they seem to appear twice, so the issue might be related to the Shelly and not necessarily this integration (`mqtt_update_period`?).
However, since the messages are identical (incl. `event_cnt`) I'd expect that the 2nd message would be ignored?

The HA entity created by this integration also toggles twice.

**Expected behavior**

Double-clicking the Shelly Button1 should result in a single toggle of the `binary_sensor.shelly_button1_xxx_double_shortpush` entity.

**Versions:**
 - Home Assistant: 2021.12.9
 - Shellies Discovery: 0.43.4
 - Shelly device firmware: 20211109-125831/v1.11.7-g682a0db

**Shellies Discovery automation:**

```yaml
alias: Shellies Discovery
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
mode: queued
max: 999
```

**Debug log:**

```txt

```

![image](https://user-images.githubusercontent.com/2406013/149094400-0e484759-7d39-402c-b89c-a5105fa7ef4a.png)
![image](https://user-images.githubusercontent.com/2406013/149094922-322cf671-45be-421a-9c55-4e0ec2d0a57a.png)

![image](https://user-images.githubusercontent.com/2406013/149094588-539b61a3-71df-4647-aef8-edfbeaabe35c.png)
Entity toggles `true` / `false` / `true` / `false`
![image](https://user-images.githubusercontent.com/2406013/149094625-e40c1aa9-08b3-42a2-8708-4c0fcaac67d1.png)

Light entity being toggled twice
![image](https://user-images.githubusercontent.com/2406013/149094727-970e9e4e-c48f-43e6-94c7-ecafc9623b8a.png)
