### ISSUE TITLE
Discovery for Shelly 1L brings up energy metering by default

### ISSUE THREAD

**Issue by SimpleUserHA** [bieniu/ha-shellies-discovery#241]
**Describe the bug**
Discovery identifies energy and power metering sensors for the Shelly 1L.  
According to my infos these don't have that feature.

In addition the INPUT sensors are both disabled by default.

**Expected behavior**
Those two sensors would not be provided for the device by default.  

Input sensors would be available like the shortpush sensors.

**Versions:**
 - Home Assistant: 2021.12.9
 - Shellies Discovery: 0.43.5
 - Shelly device firmware: 20211109-125044/v1.11.7-g682a0db

**Shellies Discovery automation:**

```yaml
- id: shellies_discovery
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      qos: 2
      use_kwh: true
      shelly1l-84CCA8AD2422:
        device_name: "Shelly Esstisch"
        relay-0: "light"
        relay-0-name: "Esstisch"
```
![shellyL-sensor-em-pm](https://user-images.githubusercontent.com/76794676/149302878-fec227b9-fa50-4d4c-bcd6-0c74a92d4864.png)

**Debug log:**

```txt
will be provided if required
```

**Comment by bieniu** [comment]
You can set the power consumption when the relay is on and then the device will send data for power and energy sensors.
![Screenshot_20220113-140126](https://user-images.githubusercontent.com/478555/149335381-4730a68a-baf3-4454-8621-38db24cc8bed.jpg)

**Comment by SimpleUserHA** [comment]
Hi @bieniu ,

sorry my fault, totally forgot about that feature.🤦‍♂️ - so that's no bug of course.

Just about the two additional findings:
- input sensors are disabled by default, while the shortpush and longpush are enabled.   For Shelly one all three are enabled by default.
Maybe I am missing the reasons for those as well. In this case, sorry in advance ;-)


![shelly1l](https://user-images.githubusercontent.com/76794676/149382952-155a6fc3-7ce3-4f05-b2ea-9d8ff5fbb346.png)
![shelly1pm](https://user-images.githubusercontent.com/76794676/149382960-5f28dc72-cc16-4931-a6f6-2cd53e5b9cc8.png)
![shelly2 5](https://user-images.githubusercontent.com/76794676/149382962-5d95be69-c7c2-4f60-b774-10145f91ba80.png)
![shellyone](https://user-images.githubusercontent.com/76794676/149382964-46ce0c1e-4710-49e3-a332-40df7be31ebd.png)

**Comment by SimpleUserHA** [comment]
Last but not least there I noticed somthing related to the naming, by using the automation as mention in first post:

Would it make sense to assign the name of the relay also as base for the energy and the power sensor, like it is done in case there is no name specified?
![naming-shelly1l](https://user-images.githubusercontent.com/76794676/149384699-0931745b-1707-451a-9cce-7575daced88d.png)
![naming-shelly1pm](https://user-images.githubusercontent.com/76794676/149384703-062aa15f-5b50-462b-b513-c65e7f1e3c62.png)

**Comment by bieniu** [comment]
> Would it make sense to assign the name of the relay also as base for the energy and the power sensor, like it is done in case there is no name specified?

The sensors use the device name as part of their names.

![image](https://user-images.githubusercontent.com/478555/149469208-ab7050de-8298-488b-86f5-e5ce21a36906.png)

**Comment by SimpleUserHA** [comment]
> > Would it make sense to assign the name of the relay also as base for the energy and the power sensor, like it is done in case there is no name specified?
> 
> **The sensors** use the device name as part of their names.
With "the sensors** you mean, sensor in general   or   energy & power meter sensors specifically?

Asking, because the input / shortpush / longpush use the relay name, rather then the device name.

Remarks:  All those things are  no big deal, I was just curious about the inconsistency and wanted to report, in case the might be a glitch.  Not matter of the default behaviour,   the scripts are running nicely and great. Thanks for your efforts.

Using the following code block for testing:
```
      shelly1-40F520011593:
        device_name: "Shelly DeviceNameTest"
        relay-0: "light"
        relay-0-name: "RelayNameTest
```
I got the following results:
 * Device with 1 relay and 1 input:
    *  shelly 1 input sensors: use the **relay name**. ✔  <img src="https://user-images.githubusercontent.com/76794676/149667331-03c91c54-58b9-4564-9901-6a60d79c489c.png" width=20% height=20%>
    * shelly 1pm input sensors: use the **relay name**. ✔  <img src="https://user-images.githubusercontent.com/76794676/149667572-1dc8d238-0a22-4261-9db5-3240bbe12e15.png" width=20% height=20%>
    * shelly 1pm energy & power meter sensors: use the device name, ❔ _but could use the relay name, as there could be a 1:1 assignment expected by default._
 * Device with 1 relay and 2 inpus (shelly one L):  <img src="https://user-images.githubusercontent.com/76794676/149667805-c3c54cc0-15b5-4636-9323-d81a6f4acf89.png" width=20% height=20%>
    * sensors input / longpush / shortpush: can not be assigned 1:1 to the relay by default, so device name is used. ✔
    * sensors energy and power could have been assigned 1:1 to the relay. ❔ _Could use the relay name, but do use the device name currently_
 * Device with 2 relays and 2 inputs (shelly 2.5):  <img src="https://user-images.githubusercontent.com/76794676/149668363-f6887da8-6606-4c6f-a6ce-95b4771be9ae.png" width=20% height=20%>
    * sensors input / longpush / shortpush: can assigned 1:1 to each relay by default and relay name is used. ✔
    * sensors energy and power could have been assigned 1:1 to each relay. ❔ _Could use the relay name, but do use the device name currently_
