### ISSUE TITLE
Wrong states on HA startup

### ISSUE THREAD

**Issue by Eyco1981** [bieniu/ha-shellies-discovery#258]
**Describe the bug**
Since the 2022.2.x releases the flooding binary sensor of my Shelly Flood often (not always) is shown as "on" after startup of Home Assistant. The MQTT topic of that device is correctly showing flood "false". I have to "reset" that state by using the developer tools.
Sometimes that also happens to Shelly Motion, but fewer times than the Shelly Flood.

**Expected behavior**
MQTT state is correctly translated to binary sensor state.

**Versions:**
 - Home Assistant: 2022.2.5
 - Shellies Discovery: 0.43.9
 - Shelly device firmware: 1.11.8 (Shelly Flood), 2.0.5 (Shelly Motion)

**Shellies Discovery automation:**
```
alias: 'MQTT: Shellies Discovery'
description: ''
trigger:
  - platform: mqtt
    topic: shellies/announce
condition: []
action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
mode: queued
max: 999
```

**Debug log:**
[python_script-debug.txt](https://github.com/bieniu/ha-shellies-discovery/files/8058240/python_script-debug.txt)
