### ISSUE TITLE
Shelly4Pro support gone due to incompatible firmware?

### ISSUE THREAD

**Issue by cpuks** [bieniu/ha-shellies-discovery#262]
I've recently started migrating HA to new hardware and found out that shellies_discovery does not detect Shelly4Pro anymore despite it's connected to MQTT server inside shellies topic, everything was working on old hardware due to fact that I did this ~ 1 yr ago.
This shelly sits on:
The current Firmware version of your Shelly device is 20201019-110845/v1.6.6_4Pro@bad181e4 No newer firmware available.

There will be no firwmare update due to lack of memory, is it possible to workaround and get support back?

**Comment by bieniu** [comment]
According to this [site](http://archive.shelly-tools.de) the newest firmware for 4Pro is `20200408-085604/v1.6.5@b075f0bf`.

**Comment by bieniu** [comment]
You didn't fill up the issue template so I don't know.

**Comment by cpuks** [comment]
**Describe the bug**
Shelly4Pro is not discovered by shellies-discovery script


**Expected behavior**
Device to be auto discovered and all entities created


**Versions:**
 - Home Assistant: 2022.2.8
 - Shellies Discovery: 0.43.10
 - Shelly device firmware: 20201019-110845/v1.6.6_4Pro

**Shellies Discovery automation:**

```yaml
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      wiata_podjazd_roleta:
        device_name: "wiata podjazd roleta"
        roller-0-name: "wiata podjazd roleta"
        roller-0-class: "shutter"
      wiata_kompostownik_roleta:
        device_name: "wiata kompostownik roleta"
        roller-0-name: "wiata kompostownik roleta"
        roller-0-class: "shutter"
      biblioteka_lampa_regal:
        device_name: "biblioteka lampa regał"
        light-0-name: "biblioteka lampa regał"
      salon_lampa_kanapa:
        device_name: "salon lampa kanapa"
        light-0-name: "salon lampa kanapa"
      kuchnia_ekspres:
        device_name: "ekspres"
        relay-0-name: "ekspres"
      robert_roleta:
        device_name: "Robert roleta"
        roller-0-name: "Robert roleta"
        roller-0-class: "shutter"
      biuro_wlacznik:
        device_name: "biuro włącznik"
        relay-0-name: "biuro włącznik"
      goscinny_wlacznik:
        device_name: "gościnny włącznik"
        relay-0-name: "gościnny włącznik"
      kotlownia_wlacznik:
        device_name: "kotłownia włącznik"
        relay-0: "light"
        relay-0-name: "kotłownia lampa"
      lazienka_parter_lustro:
        device_name: "łazienka parter lustro"
        relay-0: "light"
        relay-0-name: "łazienka parter lustro"
      lazienka_parter_wlacznik:
        device_name: "łazienka parter włącznik"
        relay-0-name: "łazienka parter włącznik"
      lazienka_pietro_lustro:
        device_name: "łazienka piętro lustro"
        relay-0: "light"
        relay-0-name: "łazienka piętro lustro"
      lazienka_pietro_wlacznik:
        device_name: "łazienka piętro włącznik"
        relay-0-name: "łazienka piętro włącznik"
      przedpokoj_wlacznik:
        device_name: "przedpokój włącznik"
        relay-0: "light"
        relay-0-name: "przedpokój lampa"
      garaz_wlacznik:
        device_name: "garaż włącznik"
        relay-0: "light"
        relay-0-name: "garaż lampy"
        relay-1: "light"
        relay-1-name: "garaż podjazd lampy"
      jagoda_roleta:
        device_name: "Jagoda roleta"
        roller-0-name: "Jagoda roleta"
        roller-0-class: "shutter"
      sypialnia_roleta:
        device_name: "sypialnia roleta"
        roller-0-name: "sypialnia roleta"
        roller-0-class: "shutter"
      taras_wlacznik:
        device_name: "taras włącznik"
        relay-0: "light"
        relay-0-name: "taras lampa 1"
        relay-1: "light"
        relay-1-name: "taras lampa 2"
      wiatrolap_wlacznik:
        device_name: "wiatrołap włącznik"
        relay-0: "light"
        relay-0-name: "wejście lampa"
        relay-1: "light"
        relay-1-name: "wiatrołap lampa"
      jagoda_wlacznik:
        device_name: "Jagoda włącznik"
      robert_wlacznik:
        device_name: "Robert włącznik"
      schody_korytarz_wlacznik:
        device_name: "schody-korytarz włącznik"
      sypialnia_wlacznik:
        device_name: "sypialnia włącznik"
```


**Debug log:**


```txt

```
