### ISSUE TITLE
Shelly 2.5 reporting shutters as always closed

### ISSUE THREAD

**Issue by mignz** [bieniu/ha-shellies-discovery#302]
**Describe the bug**
So I have migrated the Shelly 2.5 from the HomeAssistant's integration to MQTT. The only issue I am having is that the shutters are always showing as closed. Unfortunately, my shutters are unable to provide Shelly the information on their current position so I have disabled it. On MQTT, `pos=-1`, always.

**Expected behavior**
It should show as open when I open them and closed when I close them based on user interaction and not on actual position reported by the Shelly (that's my guess).

**Versions:**
 - Home Assistant: 2022.6.7
 - Shellies Discovery: 0.44.9
 - Shelly device firmware: 20220209-093016/v1.11.8-g8c7bb8d

**Shellies Discovery automation:**

```yaml
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1" # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: shellies_discovery
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model | default }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      ignore_device_model: true
      qos: 2
      shutters-livingroom-left:
        device_name: "Shutters Livingroom Left"
        roller-0-name: "Shutters Livingroom Left Roller"
        roller-0-class: "shutter"
      shutters-livingroom-right:
        device_name: "Shutters Livingroom Right"
        roller-0-name: "Shutters Livingroom Right Roller"
        roller-0-class: "shutter"
      shutters-suite:
        device_name: "Shutters Suite"
        roller-0-name: "Shutters Suite Roller"
        roller-0-class: "shutter"
      shutters-bedroom-left:
        device_name: "Shutters Bedroom Left"
        roller-0-name: "Shutters Bedroom Left Roller"
        roller-0-class: "shutter"
      shutters-bedroom-right:
        device_name: "Shutters Bedroom Right"
        roller-0-name: "Shutters Bedroom Right Roller"
        roller-0-class: "shutter"
```

**Debug log:**

```txt

```
