### ISSUE TITLE
Support for the optimistic flag in Shelly 2.5

### ISSUE THREAD

**Issue by mignz** [bieniu/ha-shellies-discovery#305]
**Is your feature request related to a problem? Please describe.**
As a reference to #302. My shutters are unable to provide positioning. HomeAssistant's solution to this is an `optimistic` flag which tries to guess what's the actual state of the roller shutter based on the switch operation.

**Describe the solution you'd like**
Support that option.

**Additional context**
From https://www.home-assistant.io/integrations/cover.mqtt/:

> If neither a state topic nor a position topic are defined, the cover will work in optimistic mode. In this mode, the cover will immediately change state (open or closed) after every command sent by Home Assistant. If a state topic/position topic is defined, the cover will wait for a message on state_topic or position_topic.
> 
> Optimistic mode can be forced, even if a state_topic / position_topic is defined. Try to enable it if experiencing incorrect cover operation (Google Assistant gauge may need optimistic mode as it often send request to your Home Assistant immediately after send set_cover_position in which case MQTT could be too slow).

The option: https://www.home-assistant.io/integrations/cover.mqtt/#optimistic

**Comment by mignz** [comment]
Have you tested this? I can't get it to work. I also believe the flag should be device specific - correct me if I'm wrong.

**Comment by bieniu** [comment]
What do yo mean you can't get it to work?

**Comment by mignz** [comment]
I mean it didn't change a thing. That's a device specific flag, correct?

This is how I'd have this configured if not using the discovery script:

```
mqtt:
  cover:
    - name: "Shutters Livingroom Right"
      state_topic: "shellies/shutters-livingroom-right/roller/0"
      command_topic: "shellies/shutters-livingroom-right/roller/0/command"
      availability:
        - topic: "shellies/shutters-livingroom-right/online"
      json_attributes_topic: "shellies/shutters-livingroom-right/info"
      payload_available: "true"
      payload_not_available: "false"
      qos: 0
      retain: true
      payload_open: "open"
      payload_close: "close"
      payload_stop: "stop"
      payload_available: "online"
      payload_not_available: "offline"
      state_opening: "open"
      state_closing: "close"
      position_open: 100
      position_closed: 0
      device_class: shutter
      optimistic: true
```

Let me know if I'm wrong.
