### ISSUE TITLE
Shelly Inputs

### ISSUE THREAD

**Issue by danriedl** [bieniu/ha-shellies-discovery#330]
**Describe the bug**

Hi dudes and dudettes,

My truenas k8s decided to die today so i had to set up everything from scratch.
I noticed, that shortpush/longpush sensors are not available anymore as stated in PR#324

I tried out the new mqtt automation triggers as in [the docs](https://github.com/bieniu/ha-shellies-discovery#how-to-use-device-automation-triggers).

This is my automation:
```yaml
alias: test_loeschen
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: ee1727fbxyz295a9ebf3bec9a4dd5251
    type: button_short_release
    subtype: button_1
    discovery_id: shelly1-YYYXXX-input-0 button_release
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.yeelight1
mode: single

```

**Expected behavior**

The light should toggle when pressing the button - which works.
But after every 30 seconds the shelly sends an update (just an `0`)in topic `shellies/shelly1-XXXYYY/input/0` which somehow triggers the automation again.

//edit: its a Shelly 1 Gen 1  in detached mode with a momentary button.

**Versions:**
 - Home Assistant: latest
 - Shellies Discovery: latest
 - Shelly device firmware: latest

**Shellies Discovery automation:**

```yaml

```

**Debug log:**

```txt

```

Thanks for the help and the script appreciate it since the beginning ❤️‍🩹
