### ISSUE TITLE
Received message on illegal discovery topic The topic contains not allowed characters. 

### ISSUE THREAD

**Issue by anubisg1** [bieniu/ha-shellies-discovery#333]
**Describe the bug**
```
Logger: homeassistant.components.mqtt.discovery
Source: components/mqtt/discovery.py:107
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 10:34:08 AM (10 occurrences)
Last logged: 10:34:08 AM

Received message on illegal discovery topic 'homeassistant/sensor/bedroom-lamp-input 0-0/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/babyroom-lamp-input 0-0/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/corridor-lamp-input 0-0/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/bathroom-lamp-input 0-0/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
Received message on illegal discovery topic 'homeassistant/sensor/entrance-lamp-input 0-0/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
```

**Expected behavior**
no errors, the discovery topic should be compliant 

**Versions:**
 - Home Assistant:  2022.10.5
 - Shellies Discovery:  1.1.1
 - Shelly device firmware:  Firmware: 20220809-124723/v1.12-g99f7e0b
Hardware: gen1 (SHSW-PM)

**Shellies Discovery automation:**

```yaml
alias: Shellies Discovery
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  - service: python_script.shellies_discovery
    data:
      id: "{{ trigger.payload_json.id }}"
      mac: "{{ trigger.payload_json.mac }}"
      fw_ver: "{{ trigger.payload_json.fw_ver }}"
      model: "{{ trigger.payload_json.model | default  }}"
      mode: "{{ trigger.payload_json.mode | default }}"
      host: "{{ trigger.payload_json.ip }}"
      qos: 2
      livingroom-motion:
        powered: battery
      kitchen-motion:
        powered: battery
      button01:
        powered: battery
      button02-white:
        powered: battery
mode: queued
max: 999

```
