### ISSUE TITLE
Unable to get "new" longpress to trigger

### ISSUE THREAD

**Issue by einarsi** [bieniu/ha-shellies-discovery#339]
I am trying to rewrite one of my automations after finally updating to a version of your script where the longpush sensor has been removed. I tried the following, copied from the automation UI:
```yaml
trigger:
  - platform: device
    device_id: b47b4dd24bc66a4e5374b8eb993f74aa
    domain: shelly
    type: long
    subtype: button
```
The action is not performed, and there is no trace of the automation ever running in the automation overview.

The device is a Shelly1 configured as a momentary switch with "Don't activate if the button is long pushed" unselected (although I have tried with it selected as well, but no change).

For now I have rewritten the automation to trigger on MQTT instead, which works fine:
```yaml
trigger:
  - platform: mqtt
    topic: shellies/shelly1-ABC123/longpush/0
    payload: "1"
```

It seems as if perhaps the MQTT longpush message event does not trigger a button long click event for the device?

**Versions:**
 - Home Assistant: 2022.11.3
 - Shellies Discovery: 2.1.0
 - Shelly device firmware: 20221027-091427/v1.12.1-ga9117d3

**Comment by bieniu** [comment]
Your trigger configuration is invalid, example of a valid configuration:
```yaml
  - platform: device
    domain: mqtt
    device_id: 8b0d2dd5099fa8d8664ab14cd4a30f87
    type: button_long_press
    subtype: button_1
    discovery_id: shelly1l-xxxxxx-input-0 button_long_press
```
Use
