### ISSUE TITLE
Shelly Motion2: No temperature when using Fahrenheit

### ISSUE THREAD

**Issue by edabe** [bieniu/ha-shellies-discovery#352]
**Describe the bug**
When customizing the Shelly Motion2 to use temperatures in Fahrenheit, no temperature entities are discovered

**Expected behavior**
The script should discover the Shelly Motion2 device with all sensors, including temperature

**Versions:**
 - Home Assistant: 2022.12.7
 - Shellies Discovery: 2.2.1
 - Shelly device firmware: `20220811-152232/v2.1.8@5afc928c`

**Shellies Discovery automation:**
```yaml
- id: "shellies_discovery"
  alias: "Shellies Discovery"
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: "{{ trigger.payload_json.id }}"
      mac: "{{ trigger.payload_json.mac }}"
      fw_ver: "{{ trigger.payload_json.fw_ver }}"
      model: "{{ trigger.payload_json.model | default }}"
      mode: "{{ trigger.payload_json.mode | default }}"
      host: "{{ trigger.payload_json.ip }}"
      qos: 2
      shellyht-746E93:
        device_name: "H&T Main Bedroom"
        force_update_sensors: true
        powered: true
        expire_after: 3600
        use_fahrenheit: true
      shellyflood-3494547185B6:
        device_name: "Flood Main Bathroom"
        force_update_sensors: true
        expire_after: 21600
        use_fahrenheit: true
      shellymotion2-8CF681105AB7:
        device_name: "Motion Main Bathroom"
        force_update_sensors: true
        powered: false
        expire_after: 3600
        use_fahrenheit: true
```

**Debug log:**
N/A

**Comment by edabe** [comment]
I've submitted a possible PR to address this issue:
https://github.com/bieniu/ha-shellies-discovery/pull/351  

I hope it's aligned with the overall idea of the script.

**Comment by bieniu** [comment]
What the temperature value does the device send via MQTT?

**Comment by edabe** [comment]
It sends the temperature already converted to the unit defined in the device, so if the configuration is set for Celsius, it will send the temp in `C`:
```
  "tmp": {
    "value": 25,
    "units": "C",
    "is_valid": true
  },
```

If it is configured in Fahrenheit, it will send the temp converted to `F`:
```
  "tmp": {
    "value": 77,
    "units": "F",
    "is_valid": true
  },
```

For reference, this is a raw payload of the `shellies/shellymotion2-8CF681105BC7/info` topic:

```
{
  "wifi_sta": {
    "connected": true,
    "ssid": "the_ssid?",
    "ip": "nnn.nnn.nnn.nnn",
    "rssi": -57
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "mqtt": {
    "connected": true
  },
  "time": "11:05",
  "unixtime": 1672416316,
  "serial": 56,
  "has_update": false,
  "mac": "8CF681105BC7",
  "cfg_changed_cnt": 0,
  "actions_stats": {
    "skipped": 0
  },
  "sleep_time": 0,
  "lux": {
    "value": 955,
    "illumination": "bright",
    "is_valid": true
  },
  "tmp": {
    "value": 77,
    "units": "F",
    "is_valid": true
  },
  "sensor": {
    "vibration": false,
    "motion": true,
    "timestamp": 1672416314,
    "active": true,
    "is_valid": true
  },
  "bat": {
    "value": 100,
    "voltage": 4.174
  },
  "charger": false,
  "update": {
    "status": "unknown",
    "has_update": false,
    "new_version": "20220811-152232/v2.1.8@5afc928c",
    "old_version": "20220811-152232/v2.1.8@5afc928c",
    "beta_version": null
  },
  "ram_total": 97280,
  "ram_free": 30744,
  "fs_size": 65536,
  "fs_free": 59272,
  "uptime": 53026,
  "fw_info": {
    "device": "shellymotion2-8CF681105BC7",
    "fw": "20220811-152232/v2.1.8@5afc928c"
  },
  "ps_mode": 0,
  "dbg_flags": 0
}
```

I wish the device would have specific topics for each sensor :(

**Comment by bieniu** [comment]
If the device sends the temp in F the sensor should be created with wrong unit. So… I don’t understand this: 

> no temperature entities are discovered

**Comment by edabe** [comment]
I configured the discovery script like this:

```
 shellymotion2-8CF681105BC7:
        device_name: "Motion Main Bathroom"
        force_update_sensors: true
        powered: false
        expire_after: 3600
        use_fahrenheit: true
```
Note the `use_fahrenheit: true` option.

And the device was discovered fine, except that it did not have any temperature:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/2922717/210094193-90cd3b73-a11c-4413-b2de-cf0ba58fcfce.png">

Note that it is missing the temperature sensor.

I tried to run the `announce` and restart HA but the device never showed any temperature.
After my change, the temperature was discovered and included in the device.
