### ISSUE TITLE
New configuration

### ISSUE THREAD

**Issue by bieniu** [bieniu/ha-shellies-discovery#36]
Example:
```yaml
- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  trigger:
    - platform: mqtt
      topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      discovery_prefix: 'hass'
      qos: 2
      shelly1-001122:
        relay-0: 'light'
      shellyswitch-9900AA:
        relay-0: 'light'
        relay-1: 'fan'
        longpush_off_delay: true
        force_update_sensors: true
      shellyswitch25-334411:
        relay-1: 'light'
        longpush_off_delay: false
        force_update_sensors: false
      shellyswitch-334455:
        mode: 'roller'
      shellyrgbw2-AABB22:
        mode: 'white'
      shellyrgbw2-AABB22:
        mode: 'rgbw'
      shellyht-2200AA:
        power: 'ac'
      shellyht-2200BB:
        power: 'battery'
      shelly1-001122:
        ext-0: 'temperature'
        ext-1: 'temperature'
        ext-2: 'temperature'
      ignored_devices:
        - shelly1-DD0011
        - shellyem-EECC22
```
