### ISSUE TITLE
Friendly name

### ISSUE THREAD

**Issue by gieljnssns** [bieniu/ha-shellies-discovery#45]
Is it possible to set the friendly name via the script?

Something like this...
```
action:
  service: python_script.shellies_discovery
  data_template:
    id: "{{ trigger.payload_json.id }}"
    mac: "{{ trigger.payload_json.mac }}"
    fw_ver: "{{ trigger.payload_json.fw_ver }}"

    shellyswitch25-XXXXXX:
      relay-0: "light"
      friendly_name-0: "Livingroom light"
      relay-1: "light"
      friendly_name-1: "Kitchen light"
      mode: "relay"
```
