### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by errecla** [bieniu/ha-shellies-discovery#49]
hi 
I see mutch error after installing shelly discovery.
cold you help me?

2020-06-01 02:04:17 ERROR (SyncWorker_5) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:24 ERROR (SyncWorker_16) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:27 ERROR (SyncWorker_7) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:30 ERROR (SyncWorker_13) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:30 ERROR (SyncWorker_9) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:30 ERROR (SyncWorker_10) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:31 ERROR (SyncWorker_16) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 560, in <module>
TypeError: 'NoneType' object is not callable
2020-06-01 02:04:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.temperatura_cpu is taking over 10 seconds
2020-06-01 02:04:33 WARNING (MainThread) [homeassistant.components.sensor] Updating command_line sensor took longer than the scheduled update interval 0:00:10
2020-06-01 02:04:34 ERROR (SyncWorker_6) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:34 ERROR (SyncWorker_15) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:34 ERROR (SyncWorker_8) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:34 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:34 ERROR (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:35 ERROR (SyncWorker_5) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:35 ERROR (SyncWorker_19) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:35 ERROR (SyncWorker_12) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
2020-06-01 02:04:35 ERROR (SyncWorker_4) [homeassistant.components.python_script.shellies_discovery.py] Error executing script: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range

**Comment by bieniu** [comment]
Probably your script configuration is wrong.

**Comment by gieljnssns** [comment]
I'm seeing the same error since the last update
```v0.20.1```: no errors
```v0.21.0```: 11x
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "shellies_discovery.py", line 783, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
IndexError: list index out of range
```
This is my config
```
id: "shellies_discovery"
alias: "Shellies Discovery"
trigger:
  - platform: mqtt
    topic: shellies/announce
action:
  service: python_script.shellies_discovery
  data_template:
    id: "{{ trigger.payload_json.id }}"
    mac: "{{ trigger.payload_json.mac }}"
    fw_ver: "{{ trigger.payload_json.fw_ver }}"

    shellyswitch25-B952FA:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyplug-s-7ADE98:
      relay-0: "fan"

    shellyplug-s-3CF0DE:
      relay-0: "fan"

    shellyswitch25-B939E5:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyswitch25-76D562:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyplug-s-7AE478:
      relay-0: "switch"

    shellyplug-s-7AE974:
      relay-0: "switch"

    shellyswitch25-76CBBD:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyswitch25-B94100:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyswitch25-693E1B:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"

    shellyswitch25-69022D:
      relay-0: "light"
      relay-1: "light"
      mode: "relay"
    # shellyswitch25-76D649:
    #   relay-0: "light"
    #   relay-1: "light"
    #   mode: "relay"
```
```
id: shellies_announce
alias: "Shellies Announce"
trigger:
  - platform: homeassistant
    event: start
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce
```
