### ISSUE TITLE
Shelly Gen1 is not discovered correctly

### ISSUE THREAD

**Issue by Spartacus68** [bieniu/ha-shellies-discovery#516]
**Describe the bug**

I am using Shelly Gen2 Discovery and thos wokrs like it shoud. In parallel I have installed the Gen1 discovery for my Shelly Uni. It is dicovered and I can see all the entities but not tagged as MQTT integration. IIt is created as Switch, binary_sensor, and only the Restart_button is detected as a mqtt device.
In the mqtt-settings it looks like this:

<img width="699" alt="image" src="https://github.com/bieniu/ha-shellies-discovery/assets/121975453/efb741be-9911-42e3-bf94-85125dbba965">
All the switches and the sensors are missing, only visible in the entity-section. How can I cahnge it?

**Versions:**
 - Home Assistant: 
 - Shellies Discovery: 
 - Shelly device firmware: 

**Shellies Discovery automation:**
```
alias: Shellies Discovery
mode: queued
max: 999
trigger:
  - platform: mqtt
    topic: shellies/announce
condition:
  - condition: template
    value_template: "{{ trigger.payload_json.gen is not defined }}"
action:
  - service: python_script.shellies_discovery
    data:
      id: "{{ trigger.payload_json.id }}"
      mac: "{{ trigger.payload_json.mac }}"
      fw_ver: "{{ trigger.payload_json.fw_ver }}"
      model: "{{ trigger.payload_json.model | default }}"
      mode: "{{ trigger.payload_json.mode | default }}"
      host: "{{ trigger.payload_json.ip }}"
```
