### ISSUE TITLE
Feature requests for shellyswitch25 roller mode

### ISSUE THREAD

**Issue by maichai** [bieniu/ha-shellies-discovery#55]
It would be great if the cover `device_class`e.g. `shutter` could also be specified, because different cover types have different icons for open and closed state. The standard icon actually does not show rollers, the rollers are better shown as cover shutters:

<img width="351" alt="Screenshot 2020-07-06 at 21 14 56" src="https://user-images.githubusercontent.com/47572832/86630942-c99e0a00-bfcd-11ea-848e-c31e0a24428e.png">

Also it would be great if the current movement direction would be shown in real time, like the ShellyForHASS does (could probably work based on the state topic and a proper value template, not sure exactly how to do it):

<img width="361" alt="Screenshot 2020-07-06 at 21 01 45" src="https://user-images.githubusercontent.com/47572832/86630829-a4110080-bfcd-11ea-9732-e66f738e17ca.png">

Finally I suggest to add support for the position feature as a sensor and as an input_number (when number is entered, the cover.set_cover_position service could be called):

<img width="368" alt="Screenshot 2020-07-06 at 21 14 47" src="https://user-images.githubusercontent.com/47572832/86631035-eb978c80-bfcd-11ea-9d7d-65e45def3826.png">

Example code for the position sensor:
```
sensor:
  - platform: mqtt
    name: "Roller Left Bedroom Position"
    icon: mdi:window-shutter-open
    unit_of_measurement: "%"
    availability_topic: "shellies/shellyswitch25-xyz/online"
    state_topic: "shellies/shellyswitch25-bed_xyz/roller/0/pos"
    json_attributes_topic: "shellies/shellyswitch25-xyz/announce"
#    json_attributes_template: "{{ tbd }}"
    value_template: "{{ value }}"
    payload_available: "true"
    payload_not_available: "false"
#    expire_after: 30
#    off_delay: 30
    force_update: false
    qos: 2
```
