### ISSUE TITLE
Question about RGBW2 shelly settings

### ISSUE THREAD

**Issue by darkkatarsis** [bieniu/ha-shellies-discovery#80]
Hey, I have a question. How to set entity_id for when you want to have mode:white?
I tried that:
```
shellyrgbw2-BC0640:
        mode: "white"
        relay-3: "kitchen"
        light-3-name: "Kitchen"
```
but unfortunately it doesn't work. I am not sure if there should be a relay. But the light-NUM parameter is not in the documentation. Can you please help?

**Comment by bieniu** [comment]
Shoud be:
```
shellyrgbw2-BC0640:
  mode: "white"
  light-1-name: "Living room"
  light-2-name: "Bedroom"
  light-3-name: "Kitchen"
```

![image](https://user-images.githubusercontent.com/478555/92729036-0392e000-f372-11ea-8a16-d360afdd0ec2.png)
