### ISSUE TITLE
Shelly 3EM Meter Energy is always 0

### ISSUE THREAD

**Issue by elfhack** [bieniu/ha-shellies-discovery#81]
The config payload is as follows

```
name: Shelly 3EM D8BFC01A7C6B Meter Energy 0
state_topic: shellies/shellyem3-D8BFC01A7C6B/emeter/0/energy
unit_of_measurement: kWh
value_template: '{{(value|float/60/1000)|round(2)}}'
availability_topic: shellies/shellyem3-D8BFC01A7C6B/online
payload_available: 'true'
payload_not_available: 'false'
force_update: 'False'
unique_id: shellyem3-d8bfc01a7c6b-emeter-energy-0
qos: 0
device:
  identifiers:
    - d8bfc01a7c6b
  name: Shelly 3EM D8BFC01A7C6B
  model: Shelly 3EM
  sw_version: 20200813-140420/v1.8.1@1b2a49be
  manufacturer: Allterco Robotics
device_class: power
platform: mqtt
```

And my payloads are around 40. It would take around 1000kWh per hour for this to be ever > 0.01?
