### ISSUE TITLE
Shelly 3EM sum meters

### ISSUE THREAD

**Issue by elfhack** [bieniu/ha-shellies-discovery#82]
Shelly3EM could use a total sum meters for all 3 phases combined, especially for current (A), power (W) and total usage (kWh). Not sure if it is possible to sum inside mqtt templates?

**Comment by bieniu** [comment]
Does device send these values via MQTT?

**Comment by elfhack** [comment]
Yeah sure :)

**Comment by bieniu** [comment]
So topics and payloads please.

**Comment by elfhack** [comment]
I use something like this right now
```
shellyem3_d8bfc01a7c6b_emeter_power:
      friendly_name: "Power"
      unit_of_measurement: 'W'
      device_class: power
      unique_id: 'shellyem3-d8bfc01a7c6b-emeter-power'
      value_template: "{{ ((states('sensor.shelly_3em_d8bfc01a7c6b_meter_power_0') | float) + (states('sensor.shelly_3em_d8bfc01a7c6b_meter_power_1') | float) + (states('sensor.shelly_3em_d8bfc01a7c6b_meter_power_2') | float))|round(1) }}"
    shellyem3_d8bfc01a7c6b_emeter_total:
      friendly_name: "Total Usage"
      unit_of_measurement: 'kWh'
      device_class: power
      unique_id: 'shellyem3-d8bfc01a7c6b-emeter-total'
      value_template: "{{ ((states('sensor.shelly_3em_d8bfc01a7c6b_meter_total_0') | float) + (states('sensor.shelly_3em_d8bfc01a7c6b_meter_total_1') | float) + (states('sensor.shelly_3em_d8bfc01a7c6b_meter_total_2') | float))|round(1) }}"
```
