### ISSUE TITLE
More states vor Shelly 2.5 in roller mode

### ISSUE THREAD

**Issue by Thomas55555** [bieniu/ha-shellies-discovery#84]
Hi,
I'm using the Shellies 2.5 in roller mode. The state for the rollers is either "Closed" or "Open". Is it possible to add the states "Closing" and "Opening", so that I can can perform an action, when a roller started to close?

Thank you, for your help, in advance.

**Comment by bieniu** [comment]
It's not possible, devices send only state `open` and `close` https://shelly-api-docs.shelly.cloud/#shelly2-5-mqtt

Ask Shelly Team about `opening` and `closing` states.

**Comment by Thomas55555** [comment]
I can ask the shelly team, but first another question:
And I also read the documentation, and they mention, that they send the `open` oder `close` command while the roller is in motion. When the motion is finished there will be the `stop` state. I also observed the mqtt messages. And I can see there, that in the moment the roller starts to open, that the `open` state will be sent.
`Nachricht 235 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0/command um 13:09:
open`
`Nachricht 236 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0 um 13:09:
open`
`Nachricht 237 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0/stop_reason um 13:09:
normal`
`Nachricht 241 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0/pos um 13:10:
100`
`Nachricht 242 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0 um 13:10:
stop`
`Nachricht 243 empfangen auf shellies/shellyswitch25-Rolladen_Ob1/roller/0/stop_reason um 13:10:
normal`
So i thought it's possible to create the `opening` state with the first `open` message and create the `opened` state with the `stop` message.
Just an idea. I don't understand how the script works...

**Comment by bieniu** [comment]
If it were a normal integration, we could infer from the previous state whether the roller is closing or opening. Unfortunately, the script only creates configuration data and passes it to the HA, so if the device doesn't send a given state, there is no way to add it.

**Comment by bieniu** [comment]
You can try to create a sensor template. If the `position` attribute increases, the cover is opening, if the `position` attribute decreases, cover is closing.

**Comment by Thomas55555** [comment]
Ah alright. Thank you. I can't use the `position` attribute, because there is no update in the attributes or the states, whilst opening or closing. But I found an alternative, which is maybe not the right way, but it's working perfectly. I want to share it here. Just in case someone is interested...
I use an automation with an [python script](https://github.com/rodpayne/home-assistant/tree/master/python_scripts) to change manually the state of the cover, when there is an mqtt event, that tells the cover is starting to open/close. After the final position is arrived, the state is overwritten by the next regular mqtt-state (opend or closed). Here is the automation:

```yaml
- alias: Set Rolladen Ob1 state opening
  trigger:
  - platform: mqtt
    topic: shellies/shellyswitch25-Rolladen_Ob1/roller/0
    payload: "open"
  action:
    - service: python_script.set_state
      data:
        entity_id: cover.ob1
        state: opening

- alias: Set Rolladen Ob1 state closing
  trigger:
  - platform: mqtt
    topic: shellies/shellyswitch25-Rolladen_Ob1/roller/0
    payload: "close"
  action:
    - service: python_script.set_state
      data:
        entity_id: cover.ob1
        state: closing
```
