### ISSUE TITLE
Button for updating devices

### ISSUE THREAD

**Issue by dodg3r** [bieniu/ha-shellies-discovery#95]
Hi.

Is it possible to update all shellies over mqtt?

If so can we get a button in hass to update the devices?

/Jerry

**Comment by bieniu** [comment]
It's possibe. You have to send `update_fw` to topic `shellies/<shellymodel>-<deviceid>/command`.

**Comment by dodg3r** [comment]
Ok, nice.

Do you think it would be possible to have one update button for all devices that needs to be updated?

**Comment by bieniu** [comment]
There is no such thing as MQTT button.

**Comment by zeridon** [comment]
Here's an automation to do it automatically (or at will)
```yaml
---
id: 'update-shelly-firmware'
alias: Update Shellies
mode: single
description: Update shellies firmware if/when available
trigger:
  - platform: state
    entity_id: group.shellies_firmware
    from: 'off'
    to: 'on'
action:
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: update_fw
```

and a sample group

```yaml
shellies_firmware:
  name: 'Shellies Firmware status'
  entities:
    - binary_sensor.shelly_1_123abc_firmware_update
    - binary_sensor.shelly_1_cba123_firmware_update
```

Notes:
 * This will update the firmware of all shelly devices in the group
 * This is extremely annoying with RBGW2 devices (disco lights more or less)
 * This does not always work with battery powerd devices
