### ISSUE TITLE
add a "name" tag for device configuration

### ISSUE THREAD

**Issue by Bascht74** [bieniu/ha-shellies-discovery#99]
**Is your feature request related to a problem? Please describe.**
Right now you have to set up the shellys with the web interface or use special URLs for new devices to config the mqtt stuff. 
I try to config as less as possible with the web interface, most of the stuff should happen in home assistant.

**Describe the solution you'd like**
Integrations like zigbee2mqtt offer a possibility to change the device name. 
Right now you added an option to set the relay/cover-name: `relay-<NUM>-name` or `roller-0-name: "Garage"`
It would be much nicer and more consitant for the most devices, if an devicename would be available. 
I know that you have to handle it with care to avoid duplicate devices, but if you are starting with it (as I am now), you would end with nice entity names not only for the relay but for everything else.

```
Example: 
shelly1-AABB9900:
        relay-0: "light"
        name: "livingroom lights"
        ext-temperature-0: true
        ext-temperature-1: true
        ext-temperature-2: true
        force_update_sensors: true
```

That way you don't need to use `relay-<NUM>-name` because the entity for the relay will have the right name. 
Right now you need to know (or to lookup) all the shelly-ids and figure out what device is behind it or vice versa...

And further more, you can exchange an device with another on (e.g. broken) and end up with still valid entities so your automatisation and so on is not broken. 

It also eliminates the need to configure this in the Shelly web interface, as this is currently the only way to achieve something similar. However, I would much rather keep the configuration as far as possible in Home Assistant and configure as little as possible in the Shelly's.

Thanks for thinking about it :-)

Sebastian
